POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
    "username": "Alan",
    "password":"Alan123",
    "email":"alan@gmail.com"
}
###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "Alan",
    "password":"Alan123"
}

###

GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json
Authorization: Token 3a47e856d570500dd19fe03567ede8448cc7cb93

{}