POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
    "username": "Arthur",
    "password":"Arthur123",
    "email":"Arthur@gmail.com"
}

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "Arthur",
    "password":"Arthur123"
}

###

GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json
Authorization: Token f36eb08e3f0ded6c8acb5149d100cc9710abc87b

{}